var data = {
    "trainLines":[
        {"name": "Westbahn", "locationsInOrder":["Wien","St. Pölten","Amstetten","St. Valentin","Linz","Wels","Attnang-Puchheim","Salzburg","Bischofshofen","Schwarzach/St. Veit","Wörgl","Innsbruck","Arlbergtunnel","Feldkirch / Buchs","Dornbirn","Bregenz","St.Margarethen / Lindau"]},
        {"name": "Summerauerbahn", "locationsInOrder":["Linz","Freistadt","Summerau","Horni Dvoriste"]},
        {"name": "Brennerbahn", "locationsInOrder":["Innsbruck","Brenner"]},
        {"name": "Tauernbahn", "locationsInOrder":["Schwarzach/St.Veit","Bad Gestein","Tauerntunnel","Spittal/Drau","Villach"]},
        {"name": "Passauerbahn", "locationsInOrder":["Wels","Neumarkt/Kalham","Schärding","Wernstein"]},
        {"name": "Mühlkreisbahn", "locationsInOrder":["Linz(Mühlkreisbhf.)","Rohrbach","Aigen/Schlägl"]},
        {"name": "Ostbahn", "locationsInOrder":["Wien","Bruck/Leitha","Nickelsdorf","Hegyeshalom"]},
        {"name": "Nordbahn", "locationsInOrder":["Wien","Hohenau","Bernhardsthal","Beclav"]},
        {"name": "Südbahn gen Spielfeld", "locationsInOrder":["Wien","Wr. Neustadt","Semmering","Mürzzuschlag","Bruck/Mur","Graz","Spielfeld / Sentilje"]},
        {"name": "Südbahn gen Rosenbach", "locationsInOrder":["Wien","Wr. Neustadt","Semmering","Mürzzuschlag","Bruck/Mur","Leoben","St.Michael/Stmk","Klagenfurt","Villach","Rosenbach / Jesenice"]},
        {"name": "Südbahn gen Arnoldstein", "locationsInOrder":["Wien","Wr. Neustadt","Semmering","Mürzzuschlag","Bruck/Mur","Leoben","St.Michael/Stmk","Klagenfurt","Villach","Arnoldstein / Tarvisio"]}
    ],
    "sbStreets":[
        {"name": "Bundesstraße 2", "locationsInOrder":["Schöngrabern","Umfang Horn","Staatsgrenze bei Neunagelberg"]},
        {"name": "Bundesstraße 6", "locationsInOrder":["Korneuburg","Ernstbrunn","Hanfthal bei Laa/Thaya"]},
        {"name": "Bundesstraße 7","locationsInOrder":["Wien","Großebersdorf","Wolkersdorf","Poysdorf","Staatsgrenze bei Drasenhofen"]},
        {"name": "Bundesstraße 9","locationsInOrder":["Schwechat","Flughafen Schwechat","Hainburg","Staatsberge bei Berg"]},
        {"name": "Bundesstraße 91","locationsInOrder":["Klagenfurt","Unterloibl","Hainburg","Staatsgrenze im Loibltunnel"]},
        {"name": "Bundesstraße 100","locationsInOrder":["Villach","Spittal/Drau","Möllbrücke","Möllbrücke","Lienz","Staatsgrenze bei Sillian","Arnbach"]},
        {"name": "Bundesstraße 148","locationsInOrder":["Ort im Innkreis","Altheim","Braunau/Inn","Staatsgrenze bei Braunau/Inn"]},
        {"name": "Bundesstraße 178","locationsInOrder":["Wörgl","St.Johann/Tirol","Lofer","Staatsgrenze bei Unken","Steinpaß"]},
        {"name": "Bundesstraße 180","locationsInOrder":["Zams","Staatsgrenze am Reschenpass"]},
        {"name": "Bundesstraße 303","locationsInOrder":["Stockerau","Hollabrunn","Staatsgrenze bei Kleinhaugsdorf"]},
        {"name": "Bundesstraße 310","locationsInOrder":["Unterweitersdorf","Freistadt","Staatsgrenze bei Wullowitz"]},
        {"name": "Bundesstraße 311","locationsInOrder":["Bischofshofen","Zell/See","Lofer"]},
        {"name": "Bundesstraße 320","locationsInOrder":["Altenmarkt/Pongau","Radstadt","Trautenfels","Liezen","Selzthal"]},
        {"name": "Wiener Außenring S. (S 1)","locationsInOrder":["Knoten Vösendorf","Knoten Schwechat","Wien","Raasdorf","Großebersdorf","Leobendorf"]},
        {"name": "Wiener Nordrand S. (S 2)","locationsInOrder":["Wien Hirschstetten","Wien Süßenbrunn"]},
        {"name": "Weinviertler S. (S 3)","locationsInOrder":["Knoten Stockerau","Hollabrunn-Süd"]},
        {"name": "Mattersburger S. (S 4)","locationsInOrder":["Mattersburg","Mattersburg","Knoten Wiener Neustadt"]},
        {"name": "Stockerauer S. (S 5)","locationsInOrder":["Knoten Stockerau","Knoten Jettsdorf","Krems"]},
        {"name": "Semmering S. (S 6)","locationsInOrder":["Knoten Seebenstein","Semmeringtunnel","Knoten Bruck/Mur","Knoten St. Michael"]},
        {"name": "Fürstenfelder S. (S 7)","locationsInOrder":["Knoten Riegersdorf/Fürstenfeld","Heiligenkreuz"]},
        {"name": "Marchfeld S. (S 8)","locationsInOrder":["Knoten Deutsch-Wagram","Marchegg"]},
        {"name": "Mühlviertler S. (S 10)","locationsInOrder":["Unterweitersdorf","Freistadt/Nord"]},
        {"name": "Arlberg S. (S 16)","locationsInOrder":["Zams","Arlbergtunnel","Bludenz/Ost"]},
        {"name": "Burgenland S. (S 31)","locationsInOrder":["Eisenstadt/Ost","Knoten Eisenstadt","Knoten Mattersburg","Oberpullendorf/Süd"]},
        {"name": "Kremser S. (S 33)","locationsInOrder":["Knoten St. Pölten","Herzogenburg","Traismauer","Knoten Jettsdorf"]},
        {"name": "Traisental S. (S 34)","locationsInOrder":["Knoten Schwadorf","Wilhelmsburg"]},
        {"name": "Brucker S. (S 35)","locationsInOrder":["Knoten Deutschfeistritz","Knoten Bruck/Mur"]},
        {"name": "Murtal S. (S 36)","locationsInOrder":["Knoten St. Michael/Stmk","Knittelfeld","Judenburg"]},
        {"name": "Klagenfurter S. (S 37)","locationsInOrder":["Scheifling","Friesach","Althofen","St. Veit a.d. Glan","Knoten Klagenfurt Nord"]}
    ],
    "autoLines":[
        {"name": "West Autobahn (A1)", "locationsInOrder":["Wien/Auhof","Knoten Steinhäusl","St. Pölten","Amstetten","Knoten Linz","Knoten Haid","Knoten Voralpenkreuz","Regau","Knoten Salzburg","Staatsgrenze am Walserberg"]},
        {"name": "Süd Autobahn (A2)", "locationsInOrder":["Wien/Inzersdorf","Knoten Vösendorf","Guntramsdorf","Wr. Neustadt","Knoten Seebenstein","Hartberg","Gleisdorf","Graz","Packsattel","Wolfsberg","Klagenfurt","Villach","Arnoldstein/Thörl-Maglern"]},
        {"name": "Südost Autobahn (A3)", "locationsInOrder":["Knoten Guntramsdorf","Ebreichsdorf","Knoten Eisenstadt"]},
        {"name": "Ost Autobahn (A4)", "locationsInOrder":["Wien/Prater","Schwechat (Flughafen)","Fischamend","Nickelsdorf"]},
        {"name": "Nord/Weinviertel Autobahn (A5)", "locationsInOrder":["Eibesbrunn","Wolkersdorf","Schrick","Poysdorf","Umfahrung Drasenhofen"]},
        {"name": "Nordost Autobahn (A6)", "locationsInOrder":["Knoten Bruckneudorf","Potzneusiedl","Gattendorf","Kittsee"]},
        {"name": "Mühlkreis Autobahn (A7)", "locationsInOrder":["Knoten Linz","Unterweitersdorf"]},
        {"name": "Innkreis Autobahn (A8)", "locationsInOrder":["Suben","Ort i. Innkreis","Ried i. Innkreis","Haag/Hausruck","Pichl/Wels","Wels","Knoten Voralpenkreuz"]},
        {"name": "Pyhrn Autobahn (A9)", "locationsInOrder":["Knoten Voralpenkreuz","Kirchdorf","Klaus","Windischgarsten","Spital/Phyrn","Bosrucktunnel","Liezen","Schoberpaß","St.Michael/Stmk","Gleinalmtunnel","Deutschfeistritz","Plabutschtunnel","Knoten Graz","Leibnitz","Spielfeld"]},
        {"name": "Tauern Autobahn (A10)", "locationsInOrder":["Knoten Salzburg","Hallein","Werfen","Bischofshofen","Knoten Eben","Tauerntunnel","St.Michael/Stmk","St. Michael/Lungau","Katschbergtunnel","Spittal/Drau","Knoten Villach"]},
        {"name": "Karawanken Autobahn (A11)", "locationsInOrder":["Knoten Villach","Karawankentunnel"]},
        {"name": "Inntal Autobahn (A12)", "locationsInOrder":["Kiefersfelden","Kufstein","Wörgl","Schwaz","Wattens","Hall i. Tirol","Knoten Innsbruck","Imst","Zams","Landeck"]},
        {"name": "Brenner Autobahn (A13)", "locationsInOrder":["Knoten Innsbruck","Brennerpaß"]},
        {"name": "Rheintal Autobahn (A14)", "locationsInOrder":["Bludenz","Feldkirch","Lauterach","Pfändertunnel","Hörbranz"]},
        {"name": "Wiener Außenring Autobahn (A21)", "locationsInOrder":["Knoten Steinhäusl","Knoten Vösendorf"]},
        {"name": "Donauufer Autobahn (A22)", "locationsInOrder":["Wien/Kaisermühlen","Langenzersdorf","Korneuburg","Stockerau"]},
        {"name": "Südosttangente Wien (A23)", "locationsInOrder":["Wien/Inzersdorf","Knoten Altmannsdorf","Knoten Prater","Knoten Kaisermühlen","Hirschstetten"]},
        {"name": "Welser Autobahn (A25)", "locationsInOrder":["Knoten Haid","Knoten Wels"]},
        {"name": "Linzer Autobahn (A26)", "locationsInOrder":["Knoten Hummelhof","Knoten Urfahr"]}
    ],
}